# Generated by Django 4.1.1 on 2022-09-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
