# Generated by Django 4.1.1 on 2022-09-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pagetag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageTag',
        ),
    ]
