# Generated by Django 4.1.1 on 2022-09-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_comments_post_comment_delete_relatedcomments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='related_post',
        ),
    ]
