# Generated by Django 4.1.1 on 2022-09-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_profilpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstaComments',
        ),
    ]
